// ui/src/pages/health/HealthContent.vue
<script setup>
import {useGetHealthQuery} from '@/apis/requests/endpoints/health/getHealth'
import {computed, ref, watch} from 'vue'
import HealthComponent from './components/HealthComponent.vue'
import LoadingPage from '@/components/page/LoadingPage.vue'
import FormattedDateAndRelativeTime from '@/components/format/FormattedDateAndRelativeTime.vue'
import ErrorBoundary from '../error/ErrorBoundary.vue'

const {data, isLoading, refetch, isRefetching, isError, error} = useGetHealthQuery(
    {},
    {refetchInterval: 1000 * 60},
)

const lastUpdateTime = ref(undefined)

watch(
    isRefetching,
    () => {
      if (!isRefetching.value && !isError.value) {
        lastUpdateTime.value = Date.now()
      }
    },
    {immediate: true},
)

const flattenComponents = (components, currentPath) => {
  const flattenedArray = []

  for (const key in components) {
    const component = components[key]
    const name = key
    const path = currentPath ? `${currentPath} / ${key}` : key
    flattenedArray.push({name, ...component})

    if (component.components) {
      const children = flattenComponents(component.children, path)
      flattenedArray.push(...children)
    }
  }

  return flattenedArray
}
const components = computed(() =>
    data.value
        ? [
          {
            name: 'Instance',
            path: 'Instance',
            status: data.value.status,
            details: data.value.details,
          },
          ...flattenComponents(data.value.components),
        ]
        : undefined,
)
</script>

<template>
  <template v-if="isLoading">
    <loading-page/>
  </template>
  <template v-else-if="isError">
    <error-boundary :error="error" :handler="refetch"/>
  </template>
  <template v-else>

    <v-card class="page-card d-flex flex-column rounded-lg" :elevation="0">
      <v-card-title>
        <div class="d-flex align-center">
          <span> Health </span>
          <v-spacer/>
          <v-tooltip location="bottom">
            <template v-slot:activator="{ props }">
              <v-btn
                  v-bind="props"
                  variant="text"
                  :disabled="isRefetching"
                  @click="refetch"
                  icon="mdi-refresh"
              />
            </template>
            Refresh
          </v-tooltip>
        </div>
        <v-tooltip location="bottom" class="text-subtitle-2">
          <template v-slot:activator="{ props }">
                <span v-bind="props" class="text-subtitle-2">
                  <template v-if="lastUpdateTime">
                    <formatted-date-and-relative-time :value="lastUpdateTime"/>
                  </template>
                </span>
          </template>
          Last Update time
        </v-tooltip>
      </v-card-title>

      <!-- refetch loading -->
      <v-progress-linear
          :active="isRefetching"
          :indeterminate="isRefetching"
          color="green"
          location="top"
          absolute
      ></v-progress-linear>

      <v-divider/>

      <v-card-text class="page-content">
        <div class="d-flex flex-column ga-3">
          <health-component
              v-for="(component, idx) in components"
              :key="idx"
              :component="component"
          />
        </div>
      </v-card-text>
    </v-card>
  </template>
</template>

<style scoped>
.page-root {
  height: 100%;
}

.page-card {
  height: 100%;
  border: 1px solid rgba(0, 0, 0, 0.2);
}

.v-theme--dark .page-card {
  border-color: rgba(255, 255, 255, 0.2);
}

.page-content {
  flex: 1;
  overflow-y: auto !important;
}
</style>

// new-ui/src/features/health/components/health-content.tsx
import type { JsonValue } from "@/apis/apiKeys";
import { useGetHealthQuery, type HealthComponentResp } from "@/apis/requests/endpoints/health/getHealth";
import { Button } from "@/components/ui/button";
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Spinner } from "@/components/ui/spinner";
import { RotateCw } from "lucide-react";
import { useMemo } from "react";
import { HealthComponent } from "./health-component";

export interface HealthComponentView {
    name: string
    path: string
    status: string
    details?: Record<string, JsonValue>
}

export function HealthContent() {
    const { data, isLoading, refetch, isRefetching, isError, dataUpdatedAt } = useGetHealthQuery(undefined, { refetchInterval: 1000 * 60 })

    const flattenComponents = (components: Record<string, HealthComponentResp>, currentPath?: string) => {
        const flattenedArray = []

        for (const key in components) {
            const component = components[key]
            const name = key
            const path = currentPath ? `${currentPath} / ${key}` : key
            flattenedArray.push({ name, path, ...component })
        }
        return flattenedArray
    }

    const components = useMemo((): HealthComponentView[] => {
        return data ? [
            {
                name: 'Instance',
                path: 'Instance',
                status: data.status,
            },
            ...flattenComponents(data.components),
        ] : []
    }, [data])

    return (
        <Card className="mx-auto w-full lg:w-3/4 xl:w-1/2">
            <CardHeader>
                <CardTitle>Health</CardTitle>
                <CardDescription>{dataUpdatedAt ? new Date(dataUpdatedAt).toLocaleString() : "-"}</CardDescription>
                <CardAction>
                    <Button variant={'ghost'} size={'icon'} onClick={() => refetch()} disabled={isRefetching}>
                        {isRefetching ? <Spinner/> : <RotateCw />}
                    </Button>
                </CardAction>
            </CardHeader>
            <CardContent>
                <div className="space-y-2">
                    {components?.map((component) => (
                        <HealthComponent key={component.path} component={component} />
                    ))}
                </div>
            </CardContent>
        </Card>
    )
}
